#!/bin/bash

if [ ! -d "bin/" ]
then
    mkdir bin
    if [ ! -d  "bin/int/" ]
    then
        mkdir bin/int
    fi
fi

gcc -o bin/int/main.o -c src/main.c $(pkg-config --cflags --libs gtk+-3.0) 
gcc -o bin/BibClient bin/int/main.o -lnsl -lm -lz -lmysqlclient 
