#!/bin/bash

if [ ! -d "bin/" ]
then
    mkdir bin
    if [ ! -d  "bin/int/" ]
    then
        mkdir bin/int
    fi
fi

gcc `pkg-config --cflags gtk+-3.0` -g -o bin/BibClient src/*.c `pkg-config --libs gtk+-3.0` -lnsl -lm -lz -lmysqlclient

